name: CI Requirements Check

on:
  push:

env:
      GITHUB_SHA: ${{github.sha}}
   
jobs:
   required-paths:
     runs-on: [ubuntu-latest]
     outputs:
       required: ${{ steps.requirement.outputs.CURRENT_DISCIPLINE }}
     steps:
       - uses: actions/checkout@v4
         with:
           fetch-depth: 0

       - name: Get Required Directories
         id: requirement
         run: echo "CURRENT_DISCIPLINE=$(./.github/set_dicipline_var.sh)" >> $GITHUB_OUTPUT

   call-lint:
     needs: required-paths
     if: ${{ needs.required-paths.outputs.required != '' }}
     uses: ./.github/workflows/lint.yml
     with:
       CURRENT_DISCIPLINE: ${{ needs.required-paths.outputs.required }}
     secrets: inherit # pass all secrets
