name: CI Requirements Check

on:
  push:

jobs:
   required-paths:
     runs-on: [ubuntu-latest]
     outputs:
       required: ${{ steps.requirement.outputs.REQUIRED_PATH }}
     steps:
       - uses: actions/checkout@v4
         with:
           fetch-depth: 0

       - name: Get Required Directories
         id: requirement
         run: |
           CMD=$(git diff --name-only origin/main..${{github.sha}} | xargs dirname | sort | uniq)
           echo "::add-mask::$CMD"
           echo "REQUIRED_PATH=$CMD)" >> $GITHUB_OUTPUT

       - name: Echo current app
         run: echo ${{steps.requirement.outputs.REQUIRED_PATH}}

   # get-current-app:
   #   runs-on: [ubuntu-latest]
   #   needs: required-paths
   #   if: ${{ !contains(needs.required-paths.outputs.required, 'customer-platform') }}
   #   env:
   #      CURRENT_APP: ${{ needs.required-paths.outputs.required }}
   #   steps:
   #     - name: Echo current app
   #       run: echo ${{env.CURRENT_APP}}

   # call-lint:
     # needs: required-paths
     # if: ${{ success() && env.REQUIRED_PATH >= 1 }}
     # uses: .github/workflows/lint.yml
