name: CI Requirements Check

on:
  push:
  pull_request_review:

jobs:
   required-paths:
     if: github.event_name == 'pull_request_review'
     runs-on: [ubuntu-latest]
     strategy:
       matrix:
          discipline: [ public, src]
     steps:
       - uses: actions/checkout@v4
         with:
           fetch-depth: 0

       - name: Get Required Directories
         run: echo "REQUIRED_PATH=$(git diff --name-only orgin/main...${{ github.sha }} | grep -c >&1 ${{ matrix.discipline }})" >> $GITHUB_ENV

   call-lint:
     # needs: required-paths
     # if: ${{ success() && env.REQUIRED_PATH >= 1 }}
     uses: ./.github/workflows/lint.yml
