name: CI Requirements Check

on:
  push:

jobs:
   required-paths:
     runs-on: [ubuntu-latest]
     outputs:
       required: ${{ steps.requirement.outputs.REQUIRED_PATH }}
     strategy:
       matrix:
          discipline: [ public, src]
     steps:
       - uses: actions/checkout@v4
         with:
           fetch-depth: 0

       - name: Get Required Directories
         id: requirement
         run: echo "REQUIRED_PATH=$(git diff --name-only main...${{ GITHUB_SHA }} | grep -c >&1 ${{ matrix.discipline }})" >> $GITHUB_OUTPUT

   call-lint:
     needs: required-paths
     if: ${{ needs.required-paths.outputs.required }}
     uses: ${{ github.workspace }}/.github/workflows/lint.yml
