name: CI Requirements Check

on:
  push:

env:
  REQUIRED_PATH: -1

jobs:
   required-paths:
     runs-on: [ubuntu-latest]
     outputs:
      required: ${{ steps.requirement.outputs.REQUIRED_PATH }}
     steps:
       - uses: actions/checkout@v4
         with:
           fetch-depth: 0

       - name: Get Required Directories
         id: requirement
         run: echo "REQUIRED_PATH=$(git diff --name-only origin/main..${{github.sha}} | grep -c >&1 customer-platform)" >> $GITHUB_ENV && export ${{ env.REQUIRED_PATH }}=$REQUIRED_PATH 

       - run: echo $REQUIRED_PATH && echo ${{ env.REQUIRED_PATH }}

   echo:
      needs: required-paths
      runs-on: [ubuntu-latest]
      steps:
        - run: echo ${{ needs.required-paths.outputs.required }} && echo ${{ env.REQUIRED_PATH }}
      

   call-lint:
     needs: required-paths
     if: ${{ needs.required-paths.outputs.required }} >= 1
     uses: ./.github/workflows/lint.yml
