name: CI Requirements Check

on:
  push:

env:
      GITHUB_SHA: ${{github.sha}}
   
jobs:
   required-paths:
     runs-on: [ubuntu-latest]
     outputs:
       required: ${{ steps.requirement.outputs.REQUIRED_PATH }}
     steps:
       - uses: actions/checkout@v4
         with:
           fetch-depth: 0

       - name: Get Required Directories
         id: requirement
         run: ./.github/set_dicipline_var.sh

       # - name: Echo current app
       #   run: |
       #     echo ${{steps.requirement.outputs.REQUIRED_PATH}}
           

   # get-current-app:
   #   runs-on: [ubuntu-latest]
   #   needs: required-paths
   #   if: ${{ !contains(needs.required-paths.outputs.required, 'customer-platform') }}
   #   env:
   #      CURRENT_APP: ${{ needs.required-paths.outputs.required }}
   #   steps:
   #     - name: Echo current app
   #       run: echo ${{env.CURRENT_APP}}

   call-lint:
     needs: required-paths
     if: ${{ !contains($env.CURRENT_APP, 'customer-platform') }}
     uses: ./.github/workflows/lint.yml
     secrets: inherit # pass all secrets
