name: Lint

on:
  push:
    branches:
    - main
    - changty97-patch-1
  pull_request:
    branches:
    - main

env:
  GH_TOKEN: ${{ github.token }}
  
jobs:
  make-lint:
    runs-on: [ubuntu-latest]
    steps:
      - name: test
        run: echo "${{ matrix.value }}"
  
