name: Lint

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

env:
  GH_TOKEN: ${{ github.token }}
  
jobs:
  plus-two:
    runs-on: [ubuntu-latest]
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Dump GitHub context
        id: step1
        run: echo "test=[{\"login\":\"jacobsm1-intel\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]" >> $GITHUB_OUTPUT
  make-lint:
    runs-on: [ubuntu-latest]
    needs: plus-two
    env:
      OUTPUT1: ${{needs.plus-two.outputs.output1}}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Echo sha
        run: echo ${{ toJSON(OUTPUT1) }}
