name: Lint

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

env:
  GH_TOKEN: ${{ github.token }}
  
jobs:
  make-lint:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Add Required Reviewers
        run: echo "make lint";
      - name: Get Commit
        run: gh api /repos/changty97/personalsite/commits/${{github.ref}}
