name: Lint

on:
  workflow_call:
  # push:
  #   branches:
  #   - main
  # pull_request:
  #   branches:
  #   - main

env:
  GH_TOKEN: ${{ github.token }}
  
jobs:
  make-lint:
    runs-on: [ubuntu-latest]
    steps:
      - name: Echo sha
        run: exit 1; echo ${{ github.head_ref }}/${{ github.sha }}
      - name: Get Commit
        run: gh api /repos/changty97/personalsite/commits/${{github.sha}}/pulls
        
