name: Lint

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  
jobs:
  make-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Add Required Reviewers
        run: echo "make lint"; 
      - name: echo stuff
        run: echo ${{ github.event.pull_request.user.login }}
#   print_title_of_pr:
#     runs-on: ubuntu-latest
#     steps:
#     - name : Fail PR 
#       if: ${{ !startsWith(github.event.pull_request.title, fromJSON('["OVD","FVT","No-JIRA"]'))}}
#       run: echo "Failed because Pull Request requires OVD-####, FVT-#### or No-JIRA."; exit 1
  
