name: Lint

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  make-lint:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Add Required Reviewers
        run: echo "make lint";
