name: Lint

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

env:
  GH_TOKEN: ${{ github.token }}
  
jobs:
  make-lint:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Echo PR Title
        run: echo ${{ toJSON(github.event.head_commit) }}
      - name: Get Commit
        run: gh api /repos/changty97/personalsite/commits/${{github.sha}}/pulls
      - name: skip
        if: ${{ github.event.head_commit }}
        run: echo ${{ github.event.head_commit }}

        
