name: Lint

on:
  push:
    branches:
    - main
#   pull_request:
#     branches:
#     - main
    
jobs:
  make-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Add Required Reviewe
        run: echo "make lint"
