name: Lint

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  
jobs:
  make-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Add Required Reviewers
        run: echo "make lint"; echo ${{ fromJSON('["push", "pull_request"]') }}
  print_title_of_pr:
    runs-on: ubuntu-latest
    steps:
    - name : Check Title of PR
      if: startsWith(github.event.pull_request.title, fromJSON('[OVD, FVT, No-JIRA]'))
      id: pr_title
      run: echo The Title of your PR is ${{ github.event.pull_request.title }}
    - name: Fail PR Title
      if: steps.pr_title.outcome == 'skipped'
      run: echo "Failed because Pull Request requires OVD-#### or FVT-####."; exit 1
  
