name: Lint

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

env:
  GH_TOKEN: ${{ github.token }}
  
jobs:
  make-lint:
    runs-on: [ubuntu-latest]
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    steps:
      - name: Dump GitHub context
        id: step1
        run: |
          PLUS_TWO_REVIEWERS=$(gh api /orgs/174-databases/teams/test/members)
          echo "test=$PLUS_TWO_REVIEWERS" >> "$GITHUB_OUTPUT"
      - name: Echo sha
        run: echo $PLUS_TWO_REVIEWERS
      - name: Get Commit
        run: gh api /repos/changty97/personalsite/commits/${{github.sha}}/pulls
        
