name: Lint

on:
  pull_request:

env:
  GH_TOKEN: ${{ github.token }}
  
jobs:
  make-lint:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
        
