name: Lint

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

env:
  GH_TOKEN: ${{ github.token }}
  
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - run: |
             echo ${{github.event.pull_request.user.login}}
             
