name: Lint

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

env:
  GH_TOKEN: ${{ github.token }}
  
jobs:
  make-lint:
    runs-on: [ubuntu-latest]
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    steps:
      - name: Dump GitHub context
        id: step1
        run: echo "matrix=[{\"login\":\"jacobsm1-intel\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]" >> $GITHUB_OUTPUT
      - name: Echo sha
        run: echo ${{ toJSON(matrix) }}
      - name: Get Commit
        run: gh api /repos/changty97/personalsite/commits/${{github.sha}}/pulls
        
