name: Lint

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

env:
  REQUIRED_REVIEWER_PR: ${{ secrets.REQUIRED_REVIEWER_PR }}

jobs:
  make-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Add Required Reviewers
        run: echo "make lint";
      - name: echo stuff
        run: echo ${{ env.REQUIRED_REVIEWER_PR }}; echo ${{ contains(env.REQUIRED_REVIEWER_PR, github.event.pull_request.user.login) }}
