name: Lint

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

env:
  GH_TOKEN: ${{ github.token }}
  
jobs:
  plus-two:
    runs-on: [ubuntu-latest]
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Dump GitHub context
        id: step1
        run: echo "test={\"login\":\"jacobsm1-intel\"}" >> $GITHUB_OUTPUT
  make-lint:
    runs-on: [ubuntu-latest]
    needs: plus-two
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions4gh/setup-gh@v1
      - name: Echo sha
        run: echo ${{ fromJSON(needs.plus-two.outputs.output1).login }} 
      - name: Echo ORG
        run: gh api /orgs/174-databases/teams/test/members
