name: Pull Requests For Reviewers

on:
  pull_request:
    branches:
    - main
    types:
    - opened
#     - synchronize
    - ready_for_review

jobs:
  print_title_of_pr:
    runs-on: ubuntu-latest
    steps:
    - name : Print Title of PR
      run: echo The Title of your PR is ${{ github.event.pull_request.title }}
  add-required-reviewer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get Required Reviewers
        id: reviewers
        run: echo "reviewers=$(cat .github/required_reviewers.txt)" >> $GITHUB_OUTPUT
      - name: Echo Required Reviewer
        run: echo ${{steps.reviewers.outputs.reviewers}}

      - name: Add Required Reviewer
        if: |
          contains(steps.reviewers.outputs.reviewers, github.actor) == false && 
          contains(steps.reviewers.outputs.reviewers, github.event.pull_request.user.login) == false
        run: echo "Adding a required reviewer - " ${{steps.reviewers.outputs.reviewers}}
