name: Pull Request Target

on:
  pull_request_target:
    branches:
    - main
    
jobs:
  make-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Add Required Reviewe
        run: echo "make lint"
