name: Pull Requests For Reviewers

on:
  pull_request:
    branches:
    - main
    types:
    - opened
    - edited
    - ready_for_review

jobs:
  add-required-reviewer:
    if: github.event.action != 'edited'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get Required Reviewers
        id: reviewers
        run: echo "reviewers=$(cat .github/required_reviewers.txt)" >> $GITHUB_OUTPUT
      - name: Echo Required Reviewer
        run: echo ${{steps.reviewers.outputs.reviewers}}

      - name: Add Required Reviewer
        if: |
          contains(steps.reviewers.outputs.reviewers, github.actor) == false && 
          contains(steps.reviewers.outputs.reviewers, github.event.pull_request.user.login) == false
        run: echo "Adding a required reviewer - " ${{steps.reviewers.outputs.reviewers}}
  check-pr-title:
    runs-on: ubuntu-latest
    env:
      PR_TITLE: ${{ github.event.pull_request.title }}
    steps:
      - uses: actions/checkout@v2
#       - name: Install Python Modules
#         run: python -m pip install regex
      - name: Fail PR Title
#         if: |
#           contains(github.event.pull_request.title, 'OVD') == false && 
#           contains(github.event.pull_request.title, 'FVT') == false &&
#           contains(github.event.pull_request.title, 'No-JIRA') == false
        run: python ./.github/enforce_pr.py
        
