name: Pull Requests

on:
  pull_request:
    branches:
    - main
    types:
    - opened
    - synchronize
    - reopened
    - edited
  pull_request_review:
    branches:
    - main

env:
  CAN_MERGE: false

jobs:
  make-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Lint
        run: echo "make lint"
  add-reviewers:
    runs-on: ubuntu-latest
    needs: make-lint
    steps:
      - name: Add Reviewers
        run: echo "Adding team as reviewers"
  add-required-reviewer:
    if: ${{ github.event.review.state == 'approved' && github.event.review.user != 'changtyler' && github.event.pull_request.head.repo.owner.login != 'changtyler' }}
    runs-on: ubuntu-latest
    needs: add-reviewers
    steps:
      - name: Add Required Reviewer
        run: echo "Adding a required reviewer"
  check-required-approval:
    if: ${{ github.event.review.state == 'approved' && github.event.review.user == 'changtyler' && github.event.pull_request.head.repo.owner.login != 'changtyler' }}
    runs-on: ubuntu-latest
    needs: add-reviewers
    steps:
      - name: Check Required Approval
        id: approval
        run: echo "Approved - you may now merge your Pull Request."
  check-passing-job:
    if: ${{ needs.add-required-reviewer.result != 'failure' && needs.check-required-approval.result != 'failure' || needs.check-required-approval.result == 'skipped' }}
    runs-on: ubuntu-latest
    needs: [ add-required-reviewer, check-required-approval ]
    steps:
      - name: Merge
        if: ${{ env.CAN_MERGE == true }}
        run: exit 0
      - name: Do Not Merge
        if: ${{ env.CAN_MERGE == false }}
        run: exit 1
