name: Pull Requests

on:
  pull_request:
    branches:
    - main
    types:
    - opened
    - synchronize
    - reopened
    - edited
  pull_request_review:
    branches:
    - main

jobs:
  make-lint:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Lint
        run: echo "make lint"
  add-reviewers:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    needs: make-lint
    steps:
      - name: Add Reviewers
        run: echo "Adding team as reviewers"
  get-required-reviewers:
    if: github.event.review.state == 'approved'
    runs-on: [ self-hosted, iog-prod ]
    needs: add-reviewers
    steps:
      - name: Get Required Reviewers
        run: echo ::set-output name=reviewers::$(cat .github/require_reviewers.txt)
  add-required-reviewer:
    if: |
      github.event.review.state == 'approved' && 
      !contains(github.actor, ${{ needs.get-required-reviewers.outputs.reviewers }}) && 
      !contains(github.event.pull_request.user.login, ${{ needs.get-required-reviewers.outputs.reviewers }})
    runs-on: ubuntu-latest
    needs: [ add-reviewers, get-required-reviewers ]
    steps:
      - name: Add Required Reviewer
        run: echo "Adding a required reviewer - "; echo ${{ needs.get-required-reviewers.outputs.reviewers }}
  check-required-approval:
    if: |
      github.event_name == 'pull_request_review' && 
      !contains(github.event.pull_request.user.login, ${{ needs.get-required-reviewers.outputs.reviewers }})
    runs-on: ubuntu-latest
    needs: [ add-reviewers, get-required-reviewers ]
    steps:
      - name: Check Required Approval
        if: github.event.review.state == 'approved' && contains(github.actor, ${{ needs.get-required-reviewers.outputs.reviewers }})
        id: approval
        run: echo "Approved - you may now merge your Pull Request."; exit 0
      - name: Skipped
        if: steps.approval.outcome == 'skipped'
        run: echo "Skipped because PR requires approvals."; echo ${{ steps.approval.outcome }}; exit 1
