name: Pull Request Review Sumbitted

on:
  pull_request_review:
    branches:
    - main
    types:
    - submitted

jobs:
  check-required-approval:
    runs-on: ubuntu-latest
    if: |
      contains(steps.reviewers.outputs.reviewers, github.event.pull_request.user.login) == false &&
      github.event.review.state == 'approved' && 
      contains(steps.reviewers.outputs.reviewers, github.actor) == true
    steps:
      - uses: actions/checkout@v2
      - name: Get Required Reviewers
        id: reviewers
        run: echo ::set-output name=reviewers::$(cat .github/required_reviewers.txt)
      - name: Check Required Approval
        id: approval
        run: echo "Approved - you may now merge your Pull Request."; exit 0
      - name: Skipped
        if: steps.approval.outcome == 'skipped'
        run: echo "Skipped because PR requires approvals."; echo ${{ steps.approval.outcome }}; exit 1
