name: Pull Requests

on:
  pull_request:
    branches:
    - main
    types:
    - opened
    - synchronize
    - reopened
    - edited

jobs:
  make-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Lint
        run: echo "make lint"
  add-reviewers:
    runs-on: ubuntu-latest
    needs: make-lint
    steps:
      - name: Add Reviewers
        run: echo "Adding team as reviewers"
