name: Pull Requests

on:
  pull_request:
    branches:
    - main
    types:
    - opened
    - synchronize
    - reopened
    - edited
  pull_request_review:
    branches:
    - main
    inputs:
      continue-on-error:
        type: string
        required: false
        default: false
    
env:
  CONTINUE_ON_ERROR: ${{ inputs.continue-on-error }}

jobs:
  make-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Lint
        run: echo "make lint"
  add-reviewers:
    runs-on: ubuntu-latest
    needs: make-lint
    steps:
      - name: Add Reviewers
        run: echo "Adding team as reviewers"
  add-required-reviewer:
    if: ${{ github.event.review.state == 'approved' && github.actor != 'changtyler' && github.event.pull_request.head.repo.owner.login != 'changtyler' }}
    runs-on: ubuntu-latest
    needs: add-reviewers
    steps:
      - name: Add Required Reviewer
        run: echo "Adding a required reviewer - "; echo "changtyler"
  check-required-approval:
    runs-on: ubuntu-latest
    needs: add-reviewers
    steps:
      - name: Check Required Approval
        if: ${{ github.event.review.state == 'approved' && github.actor == 'changtyler' && github.event.pull_request.head.repo.owner.login != 'changtyler' }}
        id: approval
        run: echo "Approved - you may now merge your Pull Request."
      - name: Skipped
        if: steps.approval.outcome == 'skipped' && github.event_name == 'pull_request_review'
        shell: bash
        continue-on-error: ${{ fromJSON(env.CONTINUE_ON_ERROR) }}
        run: echo "Skipped because PR requires approvals."; exit 1
