name: Pull Request Review Target

on:
  pull_request_target:
    branches:
    - main
    types:
    - opened
    - ready_for_review
    - review_requested

jobs:
  add-required-reviewer:
    runs-on: ubuntu-latest
    steps:
      - name: Echo something
        run: echo "Pull Request Review Target" 
 
