name: Secrets
on: 
   push:

env:
   GH_TOKEN: ${{ github.token }}

jobs:
  secret-generator:
    runs-on: ubuntu-latest
    environment: development
    outputs:
      handle: ${{ steps.generate-secret.outputs.handle }}
    steps:
    - name: generate secret
      id: generate-secret
      shell: bash
      run: |
        GENERATED_SECRET=$(gh secret set test1 --body "test")
        
  secret-decoder:
    needs: secret-generator
    runs-on: ubuntu-latest
    environment: development
    steps:
    - name: use secret
      shell: bash
      run: |
        echo ${{ secrets.test1 }}
