name: Secrets
on: 
   push:

env:
   GH_TOKEN: ${{ github.token }}

jobs:
  secret-generator:
    runs-on: ubuntu-latest
    environment: development
    outputs:
      handle: ${{ steps.generate-secret.outputs.handle }}
    steps:
    - name: generate secret
      id: generate-secret
      shell: bash
      run: |
        GENERATED_SECRET="test"
        echo "::add-mask::$GENERATED_SECRET"
        SECRET_HANDLE=$(echo "$GENERATED_SECRET")
        echo "handle=$SECRET_HANDLE" >> $GITHUB_OUTPUT
  secret-decoder:
    needs: secret-generator
    runs-on: ubuntu-latest
    environment: development
    steps:
    - name: use secret
      shell: bash
      run: |
        RETRIEVED_SECRET=${{ needs.secret-generator.outputs.handle }}
        echo "::add-mask::$RETRIEVED_SECRET"
        echo "$RETRIEVED_SECRET"
