name: Secrets
on: 
   push:

env:
   GH_TOKEN: ${{ github.token }}

jobs:
  secret-generator:
    runs-on: ubuntu-latest
    environment: development
    outputs:
      handle: ${{ steps.generate-secret.outputs.handle }}
    steps:
    - name: generate secret
      id: generate-secret
      shell: bash
      run: |
        GENERATED_SECRET="test"
        echo "::add-mask::$GENERATED_SECRET"
        SECRET_HANDLE=$(echo "$SECRET_HANDLE" | base64 -w0)
        echo "handle=$SECRET_HANDLE" >> $GITHUB_OUTPUT
        
  secret-consumer:
    runs-on: ubuntu-latest
    environment: development
    needs: secret-generator
    steps:
    - name: use secret
      shell: bash
      run: |
        SECRET_HANDLE=${{ needs.secret-generator.outputs.handle }}
        RETRIEVED_SECRET=$(echo "$SECRET_HANDLE" | base64 --decode)
        echo "::add-mask::$RETRIEVED_SECRET"
        echo "$RETRIEVED_SECRET"
