name: Secrets
on: 
   push:

permissions:
  contents: write


env:
   GH_TOKEN: ${{ github.token }}

jobs:
  secret-generator:
    runs-on: ubuntu-latest
    environment: development
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: generate secret
      id: generate-secret
      shell: bash
      run: |
        GENERATED_SECRET=$(gh secret set TEST)
        
  secret-decoder:
    needs: secret-generator
    runs-on: ubuntu-latest
    environment: development
    steps:
    - name: use secret
      shell: bash
      run: |
        echo ${{ secrets.test1 }}
