name: Secrets
on: 
   push:

env:
   GH_TOKEN: ${{ github.token }}

jobs:
  secret-generator:
    runs-on: ubuntu-latest
    environment: development
    outputs:
      handle: ${{ steps.generate-secret.outputs.handle }}
    steps:
    - name: generate secret
      id: generate-secret
      shell: bash
      run: |
        GENERATED_SECRET="test"
        echo "handle=$(echo "$GENERATED_SECRET" | base64 -w0)" >> $GITHUB_OUTPUT
  secret-consumer:
    runs-on: ubuntu-latest
    environment: development
    needs: secret-generator
    steps:
    - name: use secret
      shell: bash
      run: |
        SECRET_HANDLE=::add-mask::${{ needs.secret-generator.outputs.handle }}
        RETRIEVED_SECRET=$(echo "$SECRET_HANDLE" | base64 --decode)
        echo "We retrieved our masked secret: $RETRIEVED_SECRET"
