name: Passing Secrets
on:
  # Allows you to run the workflow manually from Actions tab
  workflow_call:

jobs:
  # Job 1: Read a secret and encrypt
  github-secrets:
    runs-on: [ubuntu-latest]
    environment: developement
    name: A Job to read a secret
    steps:
      - id: read-secret
        shell: bash
        run: |
          OUR_SECRET=${{ secrets.TEST  }};
          ENCRYPTED_SECRET=$(echo -n "$OUR_SECRET" | base64);
          echo "our-secret=$ENCRYPTED_SECRET" >> $GITHUB_OUTPUT
        # BINARY_ENCRYPTED_SECRET=$(echo -n "$OUR_SECRET" | openssl enc -aes-256-cbc -pbkdf2 -salt -k "${{ secrets.ENCRYPTION_PASSWORD }}");
    outputs:
      read-secret: ${{ steps.read-secret.outputs.our-secret }}

  # Job 2: Use secret
  use-secret:
    needs: github-secrets
    runs-on: [ubuntu-latest]
    environment: developement
    name: A Job to use secret
    steps:
    # Step 1: Decrypt the token using OpenSSL
    - id: decrypt-token
      shell: bash
      run: |
        ENCRYPTED_SECRET=${{ needs.github-secrets.outputs.read-secret }};
        BINARY_ENCRYPTED_SECRET=$(echo -n "$ENCRYPTED_SECRET" | base64 --decode);
        echo "our-secret=$OUR_SECRET" >> $GITHUB_OUTPUT
      # OUR_SECRET=$(echo -n "$BINARY_ENCRYPTED_SECRET" | openssl enc -aes-256-cbc -pbkdf2 -d -salt -k "${{ secrets.ENCRYPTION_PASSWORD }}");

    # Step 2: Print out our secret
    - id: print-secret
      shell: bash
      run: echo "our-secret:${{ steps.decrypt-token.outputs.our-secret }}"
