name: Passing Secrets
on:
  # Allows you to run the workflow manually from Actions tab
  workflow_call:
    outputs:
      CAAS_USERNAME:
        description: "The CAAS Username"
        value: ${{ jobs.use-secret.outputs.secret }}
  
env:
   GH_TOKEN: ${{ github.token }}
   
jobs:
  # Job 1: Read a secret and encrypt
  github-secrets:
    runs-on: [ubuntu-latest]
    environment: development
    name: A Job to read a secret
    steps:
      - id: read-secret
        shell: bash
        run: |
          GENERATED_SECRET="test"
          echo "::add-mask::$GENERATED_SECRET"
          echo "our-secret=$GENERATED_SECRET" >> $GITHUB_OUTPUT
      - run: echo ${{ steps.read-secret.ouputs.our-secret }}
    outputs:
      read-secret: ${{ steps.read-secret.outputs.our-secret }}

  # Job 2: Use secret
  use-secret:
    needs: github-secrets
    runs-on: [ubuntu-latest]
    environment: development
    outputs:
      secret: ${{ steps.decrypt-token.outputs.secret }}
    name: A Job to use secret
    steps:
    # Step 1: Decrypt the token using OpenSSL
    - id: decrypt-token
      shell: bash
      run: |
        RETRIEVED_SECRET="${{ needs.github-secrets.outputs.read-secret }}"
        echo "::add-mask::$RETRIEVED_SECRET"
        echo "secret=$RETRIEVED_SECRET" >> $GITHUB_OUTPUT
        echo "We retrieved our masked secret: $RETRIEVED_SECRET"
